package Common;

public class Symbols {
	public static final String [] SymbolList=new String[] {"AUDCAD","AUDCHF", "AUDJPY","AUDNZD", "AUDUSD", //"AUDSGD",
		"CADCHF", "CADJPY",
		"CHFJPY",//"CHFSGD",
		"EURAUD","EURCAD","EURCHF","EURGBP","EURJPY","EURNZD","EURUSD",
		//"EURCZK","EURDKK","EURHKD","EURNOK","EURPLN","EURSEK","EURSGD","EURTRY","EURZAR",
		"GBPAUD","GBPCAD","GBPCHF","GBPJPY","GBPNZD","GBPUSD",
		//"GBPDKK","GBPSEK","GBPTRY","GBPNOK",
		//"NOKJPY","NOKSEK",
		//"NZDCAD","NZDCHF",
		"NZDJPY","NZDUSD",
		//"SEKJPY","SGDJPY",
		"USDCAD","USDCHF","USDJPY", 
		//"USDCZK","USDDKK","USDHKD","USDMXN","USDNOK","USDPLN","USDSEK","USDSGD","USDTRY","USDZAR","USDCNH",
		"XAUUSD","XAGUSD",
		//"XAGEUR","XAUEUR" 
		
		
		"CL-OIL","SPI200","SPX500","DAX30","DJ30","FTSE100","Nikkei225","USDX","HSI","CHINA50"
	};
}
